# Generated by Django 4.0.1 on 2022-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('district', models.CharField(choices=[('Kishoreganj District', 'Kishoreganj District'), ('Gopalganj District', 'Gopalganj District'), ('Gazipur District', 'Gazipur District'), ('Faridpur District', 'Faridpur District'), ('Dhaka District', 'Dhaka District'), ('Narsingdi District', 'Narsingdi District'), ('Narayanganj District', 'Narayanganj District'), ('Munshiganj Districtt', 'Munshiganj District'), ('Manikganj District', 'Manikganj District'), ('Madaripur District', 'Madaripur District'), ('Rajbari District', 'Rajbari District'), ('Shariatpur District', 'Shariatpur District'), ('Tangail District', 'Tangail District'), ('Cumilla District', 'Cumilla District'), ('Chattogram District', 'Chattogram District'), ('Chandpur District', 'Chandpur District'), ('Brahmanbaria District', 'Brahmanbaria District'), ('Bandarban District', 'Bandarban District'), ('Noakhali District', 'Noakhali District'), ('Lakshmipur District', 'Lakshmipur District'), ('Khagrachhari District', 'Khagrachhari District'), ('Feni District', 'Feni District'), ('Cox’s Bazar District', 'Cox’s Bazar District'), ('Rangamati District', 'Rangamati District'), ('Patuakhali District', 'Patuakhali District'), ('Jhalokati District', 'Jhalokati District'), ('Bhola District', 'Bhola District'), ('Barishal District', 'Barishal District'), ('Barguna District', 'Barguna District'), ('Pirojpur District', 'Pirojpur District'), ('Sylhet District', 'Sylhet District'), ('Sunamganj District', 'Sunamganj District'), ('Moulvibazar District', 'Moulvibazar District'), ('Habiganj District', 'Habiganj District'), ('Khulna District', 'Khulna District'), ('Jhenaidah District', 'Jhenaidah District'), ('Jashore District', 'Jashore District'), ('Chuadanga District', 'Chuadanga District'), ('Bagerhat District', 'Bagerhat District'), ('Satkhira District', 'Satkhira District'), ('Narail District', 'Narail District'), ('Meherpur District', 'Meherpur District'), ('Magura District', 'Magura District'), ('Kushtia District', 'Kushtia District'), ('Chapainawabganj District', 'Chapainawabganj District'), ('Natore District', 'Natore District'), ('Joypurhat District', 'Joypurhat District'), ('Naogaon District', 'Naogaon District'), ('Bogura District', 'Bogura District'), ('Sirajganj District', 'Sirajganj District'), ('Rajshahi District', 'Rajshahi District'), ('Pabna District', 'Pabna District'), ('Dinajpur District', 'Dinajpur District'), ('Gaibandha District', 'Gaibandha District'), ('Rangpur District', 'Kishoreganj District'), ('Rangpur District', 'Rangpur District'), ('Panchagarh District', 'Panchagarh District'), ('Nilphamari District', 'Nilphamari District'), ('Lalmonirhat District', 'Lalmonirhat District'), ('Kurigram District', 'Kurigram District'), ('Thakurgaon District', 'Thakurgaon District'), ('Sherpur District', 'Sherpur District'), ('Netrokona District', 'Netrokona District'), ('Mymensingh District', 'Mymensingh District'), ('Jamalpur District', 'Jamalpur District')], max_length=150)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('my_file', models.FileField(blank=True, upload_to='document')),
            ],
        ),
    ]
